name: build shaders to zip

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Show Working directory
      run: ls


    - name: Zip Chocapic13_V6_High artifact
      run: zip Chocapic13_V6_High.zip ./Chocapic13_V6_High/* -r

    - name: Publish Chocapic13_V6_High artifact
    - uses: tfc-survival/upload-artifact@v0.9
      with:
        name: Chocapic13_V6_High.zip
        path: ./Chocapic13_V6_High.zip


    - name: Zip SEUS_Renewed_TFG artifact
      run: zip SEUS_Renewed_TFG.zip ./SEUS_Renewed_TFG/* -r

    - name: Publish SEUS Renewed TFG v1.0 artifact
    - uses: tfc-survival/upload-artifact@v0.9
      with:
        name: SEUS Renewed TFG v1.0.zip
        path: ./SEUS Renewed TFG v1.0.zip


    - name: Zip Sildurs_Vibrant_Shaders artifact
      run: zip Sildurs_Vibrant_Shaders.zip ./Sildurs_Vibrant_Shaders/* -r

    - name: Publish Sildurs_Vibrant_Shaders artifact
    - uses: tfc-survival/upload-artifact@v0.9
      with:
        name: Sildurs_Vibrant_Shaders.zip
        path: ./Sildurs_Vibrant_Shaders.zip
